//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NBD_SBEntities : DbContext
    {
        public NBD_SBEntities()
            : base("name=NBD_SBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<LABOUR_REQUIREMENT> LABOUR_REQUIREMENT { get; set; }
        public virtual DbSet<LABOUR_SUMMARY> LABOUR_SUMMARY { get; set; }
        public virtual DbSet<MATERIAL> MATERIALs { get; set; }
        public virtual DbSet<MATERIAL_REQ> MATERIAL_REQ { get; set; }
        public virtual DbSet<PROD_TEAM> PROD_TEAM { get; set; }
        public virtual DbSet<PROD_TOOL> PROD_TOOL { get; set; }
        public virtual DbSet<PROJECT> PROJECTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TASK> TASKs { get; set; }
        public virtual DbSet<TOOL> TOOLs { get; set; }
        public virtual DbSet<WORKER> WORKERs { get; set; }
        public virtual DbSet<WORKER_TYPE> WORKER_TYPE { get; set; }
    }
}
